# Generated by Django 5.2.8 on 2025-11-20 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebClubAlmacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
