# Generated by Django 5.2.7 on 2025-11-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apaterno', models.CharField(max_length=100)),
                ('amaterno', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(blank=True, max_length=128, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo_usuario', models.CharField(max_length=50)),
            ],
        ),
    ]
