# Generated by Django 5.2.7 on 2025-11-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('usuario', models.AutoField(primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apaterno', models.CharField(max_length=100)),
                ('amaterno', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo_usuario', models.CharField(max_length=50)),
            ],
        ),
    ]
