# Generated by Django 5.2.7 on 2025-11-18 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebClubAlmacen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
