# Generated by Django 5.2.7 on 2025-12-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebClubAlmacen', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='index/')),
                ('categoria', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('modelo_origen', models.CharField(max_length=100)),
                ('objeto_id', models.IntegerField()),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
