# Generated by Django 5.2.7 on 2025-11-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebClubAlmacen', '0002_remove_usuario_fecha_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
