# Generated by Django 5.2.7 on 2025-11-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebClubAlmacen', '0004_beneficio_blog_directorio_enlaceutil_invitacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AddField(
            model_name='beneficio',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficio',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directorio',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='enlaceutil',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='directorio',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='directorio',
            name='direccion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='directorio',
            name='telefono',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='nuevocomercio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nuevocomercio',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='streaming',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
